- src/Console/MakeCommand.php
This PR updates the `make:volt` command to include an example when prompting for the missing "name" argument:
The goal of these placeholders is typically to prevent a trip to the docs for those that want to use conventional naming. In this case, the example was taken straight from the documentation and tells the user that a lower-case name is typical.
The placeholder feature is only supported on Laravel 10.17 or later, where Laravel Prompts is included. Previous versions that use Symfony's prompts will continue to work without seeing the placeholder.
> [1.x] Add example to `make:volt` prompt

- functions.php
- src/CompileContext.php
- src/Compiler.php
- src/Compilers/Interfaces.php
- src/Compilers/ProtectedMethods.php
- src/Compilers/PublicMethods.php
- src/Compilers/Traits.php
- src/ComponentFactory.php
- src/Exceptions/TraitOrInterfaceNotFound.php
- src/Options/UsesOptions.php
- tests/.pest/snapshots/Feature/ComponentTest/generated_code_with_data_set__dataset__component_with_external_interfaces_blade_php______tests_Feature_resources_view___de_php__.snap
- tests/Feature/Compiler/UsesTest.php
- tests/Feature/CompilerContext/UsesFileUploadsTest.php
- tests/Feature/CompilerContext/UsesPaginationTest.php
- tests/Feature/CompilerContext/UsesTest.php
- tests/Feature/ComponentTest.php
- tests/Feature/resources/views/livewire/component-with-external-interfaces.blade.php
- tests/Fixtures/IncrementInterface.php
This pull request closes https://github.com/livewire/volt/issues/10, and it allows to specify that the given component implements an given interface. Example:
```php
<?php
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use function Livewire\Volt\uses;
uses([HasTable::class, InteractsWithTable::class]); ?>
$table = fn(Table $table): Table => $table
->query(Product::query())
->columns([
TextColumn::make('name'),
])
->filters([
// ...
]); ?>
<div>
...
```
> [1.x] Adds `uses` interface support

- src/Volt.php
- src/VoltManager.php
- src/VoltServiceProvider.php
- tests/Feature/FunctionalComponentTest.php
- tests/Feature/FunctionalFolioTest.php
This pull request fixes https://github.com/livewire/volt/issues/21, by adding a new `assertSeeVolt` that allows you test that a given response contains a fragment:
```php
$this->get('/page-with-@volt-directive')->assertSeeVolt('fragment-component');
```
> [1.x] Adds assertSeeVolt assertion

- src/ComponentFactory.php
This pull request fixes https://github.com/livewire/volt/issues/25 and addresses the issue with the Class API when used with multiple fragments.
The explanation might be a bit intricate, but if the blade view is already in opcache, the behavior of `new class extends` will differ from subsequent requests after the initial one:
```
// my-component.blade.php...
echo get_class(new class extends A);
// First request with op cache enabled
require 'my-component.blade.php'; // 1111
require 'my-component.blade.php'; // 2222
require 'my-component.blade.php'; // 3333
// Second request with op cache enabled
require 'my-component.blade.php'; // 1111
require 'my-component.blade.php'; // 1111
require 'my-component.blade.php'; // 1111
```
So, this pull request simply "invalidates" the opcache for any …
> [1.x] Fixes Class API when used with multiple fragments

- src/ComponentFactory.php
fixes #27 
```
Call to undefined function Livewire\Volt\opcache_invalidate()
```
> Avoid throwing error when OpCache isn't installed

- src/Compilers/PublicMethods.php
- tests/Feature/Compiler/DehydrateTest.php
- tests/Feature/Compiler/HydrateTest.php
- tests/Feature/Compiler/UpdatedTest.php
- tests/Feature/Compiler/UpdatingTest.php
This pull request fixes an issue on property hook arguments, where the property "name" was been sent as argument:
```php
// before
updated(query: fn (string $name, string $newValue) => /** ... */); ?>
// after
updated(query: fn (string $newValue) => /** ... */); ?>
```
Note that having `$name` there does not make sense - as the hook is only fired for the `query` property as specified.
> [1.x] Fixes sending "name" as property hook argument

- src/Precompilers/ExtractTemplate.php
- tests/.pest/snapshots/Feature/FunctionalComponentTest/generated_code_with_data_set__dataset__component_with_user_imports_blade_php______tests_Feature_resources_view___de_php__.snap
- tests/Feature/FunctionalComponentTest.php
- tests/Feature/resources/views/functional-api/component-with-user-imports.blade.php
- tests/Unit/Precompilers/ExtractTemplateTest.php
This pull request fixes https://github.com/livewire/volt/issues/36, and fixes PHP scripts included on bottom of a Volt component. Because, sometimes, there is no `?>` ending tags, that specific script was not being considered as "script" by our pre-compiler.
> [1.x] Fixes bottom script being included as template

- composer.json
- tests/Feature/ClassFolioTest.php
- tests/Feature/FunctionalFolioTest.php
- tests/Feature/resources/views/class-api-pages/authorization-on-render.blade.php
- tests/Feature/resources/views/class-api-pages/authorization-with-mount.blade.php
- tests/Feature/resources/views/class-api-pages/page-with-view-content.blade.php
- tests/Feature/resources/views/functional-api-pages/authorization-on-render.blade.php
- tests/Feature/resources/views/functional-api-pages/page-with-view-content.blade.php
This pull request adds integration tests with Folio's new `render` function: https://github.com/laravel/folio/pull/100.
> [1.x] Adds integration tests with `render`

- src/VoltManager.php
Fixes https://github.com/livewire/volt/issues/39.
This pull request fixes the `Segmentation fault` on `route:cache` when using `Volt::route`.
> [1.x] Fixes `Segmentation fault` on `route:cache`

- src/Console/MakeCommand.php
- stubs/volt-component-class.stub
This pull request adds `--class` option to `volt:make` command:
```php
<?php // php artisan make:volt counter --class
use Livewire\Volt\Component;
new class extends Component {
//
}; ?>
<div>
//
</div>
```
> [1.x] Adds `--class` option to `make:volt` command

- src/VoltManager.php
- tests/Feature/FunctionalComponentTest.php
This pull request adds `withQueryParams` to the `Volt::test` API: https://livewire.laravel.com/docs/testing#setting-url-parameters.
Fixes https://github.com/livewire/volt/issues/50.
> [1.x] Adds `withQueryParams`

- src/Volt.php
- src/VoltManager.php
- tests/.pest/snapshots/Feature/FunctionalComponentTest/generated_code_with_data_set__dataset__component_with_logged_user_blade_php______tests_Feature_resources_view___de_php__.snap
- tests/Feature/FunctionalComponentTest.php
- tests/Feature/resources/views/functional-api/component-with-logged-user.blade.php
This pull request a missing `actingAs` method to the Volt's facade.
> [1.x] Adds `actingAs` to Volt facade

- src/CompilerVersion.php
- src/Precompilers/Concerns/ExtractsImports.php
- src/Precompilers/ExtractFragments.php
- src/Precompilers/ExtractTemplate.php
- tests/Feature/AnonymousComponentTest.php
- tests/Feature/FunctionalFolioTest.php
- tests/Feature/resources/views/functional-api-pages/page-with-fragment-using-imports-on-template.blade.php
- tests/Fixtures/Status.php
Fixes https://github.com/livewire/volt/issues/62.
This pull requests fixes an issue where imports of the page/view definition where not being used on the compiled fragment's template.
> [1.x] Fixes imports used on fragments

- src/Component.php
Fixes https://github.com/livewire/volt/issues/64.
We've not noticed, but Livewire already calls the `rendering` method.
> [1.x] Removes custom `rendering` call

- composer.json
- src/Actions/CallMethod.php
- src/LivewireManager.php
- tests/Feature/ClassComponentTest.php
- tests/Feature/FunctionalComponentTest.php
This pull request fixes rules missing exception message, after recent changes on Workbench and Livewire 3 (https://github.com/livewire/livewire/pull/7266).
> [1.x] Fixes rules missing exception message

- functions.php
- src/Actions/ReturnRules.php
- src/CompileContext.php
- tests/.pest/snapshots/Feature/FunctionalComponentTest/generated_code_with_data_set__dataset__component_with_rules_blade_php______tests_Feature_resources_view___de_php__.snap
- tests/Feature/CompilerContext/RulesTest.php
- tests/Feature/FunctionalComponentTest.php
- tests/Feature/resources/views/functional-api/component-with-rules.blade.php
Fixes: https://github.com/livewire/volt/pull/67.
Test suite failing because of: https://github.com/livewire/volt/pull/70.
This pull request fixes an issue with the `rules` function where is not possible to defer the rules resolution like so:
```php
rules(fn () => [
'name' => ['required', 'min:6'],
'email' => ['required', 'email', 'not_in:'.Auth::user()->email]
]);
```
> [1.x] Allows to specify rules as closure

- functions.php
- tests/.pest/snapshots/Feature/FunctionalComponentTest/generated_code_with_data_set__dataset__component_state_with_without_keys_blade_php______tests_Feature_resources_view___de_php__.snap
- tests/Feature/FunctionalComponentTest.php
- tests/Feature/resources/views/functional-api/component-state-with-without-keys.blade.php
Hi there! I found a bug. If the states contain an element without a key and an element with a key, an error will occur and a component with a numeric property will be generated. my pr fixes this case
Example:
```php
state(['article', 'count' => 0]);
```
I'll get an error
`syntax error, unexpected token "$", expecting variable`
Generated component
```php
new class extends Component implements Livewire\Volt\Contracts\FunctionalComponent
{
public static CompileContext $__context;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
public $0;
public $count;
```
`public $0;`
> fix: State properties

- functions.php
- src/Actions/ReturnTitle.php
- src/CompileContext.php
- tests/Feature/Actions/ReturnTitleTest.php
- tests/Feature/CompilerContext/TitleTest.php
This PR adds the ability to set titles using closures when using the functional API.
As of 1.5.0 it's not possible to make "computed" titles using the functional API. To achieve this, the class-based API has to be used using the `rendering` lifecycle hook as described [in the Volt documentation](https://livewire.laravel.com/docs/volt#modifying-the-view-instance).
By allowing closures to be passed to the `title` function it will allow developers to defined titles like so:
```php
state(['firstName' => 'Tom']);
title(fn () => 'This is the title');
// Or even
title(fn () => "Hi $this->firstName");
```
I will submit a separate PR for documentation.
> [1.x] Allow setting title using a closure in functional API

- composer.json
- functions.php
- src/CompileContext.php
- src/FragmentAlias.php
- src/Options/StateOptions.php
- src/Options/UsesOptions.php
- src/VoltManager.php
- tests/Feature/FunctionalComponentTest.php
- tests/Feature/resources/views/functional-api/navigate/with-model-route-binding.blade.php
This pull request adds tests for different model route binding cases. Waiting for https://github.com/laravel/framework/pull/49432, and fixes https://github.com/livewire/volt/issues/80. I will need to bump the framework version on this.
> [1.x] Adds tests for model route binding

- src/Console/InstallCommand.php
- src/Console/MakeCommand.php
- stubs/VoltServiceProvider.stub
This pull request replaces https://github.com/livewire/volt/pull/76, and it fixes the non-usage of `livewire.view_path` configuration.
> [1.x] Fixes non-usage of `livewire.view_path` configuration

- src/MountedDirectories.php
Volt is already doing the work to save multiple component paths, we just need to use those saved paths when setting up the namespace.
This provides support for easily adding paths to components in custom packages like:
```php
use Illuminate\Support\ServiceProvider;
use Livewire\Volt\Volt;
class PackageServiceProvider extends ServiceProvider
{
/**
* Bootstrap the application services.
*/
public function boot()
{
$this->app->booted( function() {
Volt::mount( __DIR__.'/../resources/views/livewire' );
} );
}
}
```
Fixes #87 and #92 and #94
> Use paths from object property, not local variable

- src/Component.php
- src/ComponentFactory.php
- src/VoltServiceProvider.php
Can we please remove final from the render method? 
I'm playing with adding support for rendering react/vue components inside of volt components with https://github.com/ijpatricio/mingle, but naturally it needs to be able to hijack the render method to function.
I can't think of any reasons why removing the final keyword would be a breaking change here.
> Remove final from render

- src/Console/MakeCommand.php
I appreciate the check that `make:test` provides when you are using a starter kit or already have a Pest or a PHPUnit test created in the project, and I think it makes a great addition to Volt, as well.
I always forget to add the `--class` option when creating a new Volt component for my projects.
This adds a `usingClass` function to check to see if any Livewire Volt components already exist in the `Volt::paths()` and if that is identified as a Class component, then it will default to using the Class component stub when the `volt:make` command is run.
Additionally, I did add a `--functional` option to the command due to the fact that there are some folks who might want Class & Functional components to exist in the same project. While that can be written manually, I figured it wouldn't …
> Make class component if project uses Volt Class components

- src/Console/MakeCommand.php
- tests/Feature/Console/MakeCommandTest.php
Hi,
looking over Caleb Porzio's Livewire screencasts today, I noticed that the `make:volt`command doesn't support the dot notation, that is already present in `make:livewire` command.
Here's an example of both outputs:
```bash
php artisan make:volt component/index
INFO  Volt component [resources/views/livewire/component/index.blade.php] created successfully.  
```
```bash
php artisan make:volt component.index
INFO  Volt component [resources/views/livewire/component.index.blade.php] created successfully.  
```
```bash
php artisan make:livewire component.index
COMPONENT CREATED  🤙
CLASS: app/Livewire/Component/Index.php
VIEW:  resources/views/livewire/component/index.blade.php 
```
I thought this would be a nice alignment to the way things operate. I tried to make the changes as minimal as …
> Support the dot in the make:volt command
